---
check_definitions:
  - name: "check_color_tags_name"
    class_name: "ColorTagsCheck"
    file_path: "tags_check.py"
  - name: "netpicker_api"
    file_path: "netpicker_api.py"
  - name: "print_ok"
    class_name: "PrintOKCheck"
    file_path: "print_ok.py"