---
check_definitions:
  - name: "netpicker_device_check"
    class_name: "NetpickerDeviceInterfaceCheck"
    file_path: "checks/netpicker_device_check.py"

queries:
  - name: "device_interface_details"
    file_path: "checks/device_interface_details.gql"